### ISSUE TITLE
Can't parse any .rt file

### ISSUE THREAD

**Issue by slepkaviba** [gja/react-templatify#2]
While I try to parse I got:

ReactTransformify: myfile.rt Document should have a root element while parsing file: myfile.rt

Running rt myfile.rt works and file is parsed properly. It fails on any react template I have.

**Comment by gja** [comment]
Can you share a sample project?

Every .rt file must have a single root node.

**Comment by slepkaviba** [comment]
How comes a single one? Even in examples rt-require is multipled, and code checks if "length === 0".

**Comment by gja** [comment]
https://facebook.github.io/react/tips/maximum-number-of-jsx-root-nodes.html

**Comment by gja** [comment]
@slepkaviba if you post a sample project that fails, i can try to help you out

**Comment by slepkaviba** [comment]
Yea, but I think that templates can handle rt-require and they are converted into the require() statements, so they do not count as root node in the end for JSX.

Btw - deamdify is not needed as we can parse --modules commonjs and then even lodash is included properly.

And.. I've prepared a sample project. And all works flawless... It means in mine I did some config mess..

**Comment by gja** [comment]
@slepkaviba yes, that's correct. You can do rt-require, they do not count

**Comment by slepkaviba** [comment]
I just don't understand why "rt myfile.rt" works, and browserify can't manage...(╯°□°）╯︵ ┻━┻

**Comment by slepkaviba** [comment]
Btw - I've moved rt-require inside of div... And it worked - now stucks on other file, that is:

``` html
<div>
<p>Sample content</p>
</div>
```

With same error...

**Comment by slepkaviba** [comment]
Ok, I totally dont know - I think that it was some encoding messed up.. Now without touching the templates everything compiles... Should I blame Windows?

**Comment by maqqju** [comment]
We had a similar issue when trying to run `react-templatify` from a `Gruntfile`.

The problem was that we still had our `browserify` tasks defined inside the `package.json` - and so the files were being `browserify`ed twice. Once removed, all was ok.
