### ISSUE TITLE
Upgrade to react-templates v0.5.0

### ISSUE THREAD

**Issue by delijah** [gja/react-templatify#6]
Are there any plans to upgrade to react-templates v0.5.0?

**Comment by gja** [comment]
Yes.  Well upgrade later today

## 

Tejas Dinkar

**Comment by gja** [comment]
This is done

**Comment by gja** [comment]
Um, wait. React-Templates v0.5.0? I see 0.4.4 as latest stable

**Comment by delijah** [comment]
Yeah they write 0.4.4 on their github site and also on npm it's 0.4.4, but if you have a look a the tags on github, there is an entry with 0.5.0. I have no information if this is stable or not.
